"""empty message

Revision ID: 98977aa751c8
Revises: 00dbdc6275c9
Create Date: 2018-01-21 01:47:03.196641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98977aa751c8'
down_revision = '00dbdc6275c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humidities_data'), 'humidities', ['data'], unique=False)
    op.create_table('luminosities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_luminosities_data'), 'luminosities', ['data'], unique=False)
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperatures_data'), 'temperatures', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperatures_data'), table_name='temperatures')
    op.drop_table('temperatures')
    op.drop_index(op.f('ix_luminosities_data'), table_name='luminosities')
    op.drop_table('luminosities')
    op.drop_index(op.f('ix_humidities_data'), table_name='humidities')
    op.drop_table('humidities')
    # ### end Alembic commands ###
